### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by distratul** [kaganus/CSGOItemParserForWeaponsPlugin#1]
Hi. I have installed the folders on my pc, on csgo steam folder. I  have installed java in windows 10 and when i hit the run command like in your description doesn't create the folder "addons" and doesn't create any weapons configs.

**Comment by distratul** [comment]
somebody maybe explaines me how to do it work? Thanks in advance !

**Comment by distratul** [comment]
I will donate !

**Comment by distratul** [comment]
Where i must write the code? java -jar weaponsconfig.jar "D:\Program Files\Steam\steamapps\common\Counter-Strike Global Offensive\csgo" english

**Comment by kaganus** [comment]
this is developed to be used with a csgo dedicated server installation. if you want to use this with your game client installation, make sure to create the folder "D:\Program Files\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\addons\sourcemod\configs\weapons\" first, then launch Command Prompt (cmd.exe), and paste java -jar weaponsconfig.jar "D:\Program Files\Steam\steamapps\common\Counter-Strike Global Offensive\csgo" english

**Comment by kaganus** [comment]
or wherever your game is installed on you hard drive.

D:\Program Files\Steam\steamapps\common\Counter-Strike Global Offensive\csgo is just an example

**Comment by distratul** [comment]
Believe me that i've tried all the possible solutions...still not working for me. it says unable to fiind jar. file. Mybe it is a problem from java because in one year had been updated frequently. Thanks in advance

**Comment by distratul** [comment]
Error: Unable to access jarfile weaponsconfig.jar

**Comment by kaganus** [comment]
that is certainly not an issue with this project. you have to research how to run jar files with java executable
